title: Grandes películas y pequeños bodrios
author: Capitan cámara
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Aquí tienes una referencia a algunos títulos alegres y perspicaces.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
